---
- name: Install python-requests
  yum:
    name: python-requests
    state: latest

- name: Clone contrail-ansible-deployer
  git:
    repo: "{{ contrail_deployer_branch | get_deployer_repo }}"
    dest: /root/contrail-ansible-deployer
    force: yes
    version: "{{ contrail_deployer_branch }}"

- name: Populate contrail-ansible-deployer/config/instances.yaml
  template:
    src: "{{ instances_template }}"
    dest: /root/contrail-ansible-deployer/config/instances.yaml

- name: Create config directory
  file:
    path: "{{ vagrant_root }}/config"
    state: directory
  delegate_to: localhost

- name: Populate config/instances.yaml
  template:
    src: "{{ instances_template }}"
    dest: "{{ vagrant_root }}/config/instances.yaml"
  delegate_to: localhost

- name: Install kvm for DPDK vrouter
  shell:  modprobe -r kvm_intel

- name: Change k8s version in roles files
  replace:
    path: "/root/contrail-ansible-deployer/playbooks/roles/k8s/tasks/main.yml"
    regexp: 'k8s_version: \"(\d+)\.(\d+)\.(\d+)\"'
    replace: "k8s_version: \"1.14.8\""
